name: "test"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test-jdk8:
    name: "Test JDK8"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Build
        run: make classes
      - name: Run
        run: make SKIP_AGENT_TESTS=1 all

  test-jdk11:
    name: "Test JDK11"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build
        run: make classes
      - name: Run
        run: make SKIP_AGENT_TESTS=1 all

  test-jdk14:
    name: "Test JDK16"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Build
        run: make classes
      - name: Run
        run: make SKIP_AGENT_TESTS=1 all
