name: "test"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test-jdk8:
    name: "Test JDK8"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build
        run: make classes
      - name: Run
        run: make SKIP_AGENT_TESTS=1 all

  test-jdk11:
    name: "Test JDK11"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build
        run: make classes
      - name: Run
        run: make SKIP_AGENT_TESTS=1 all

  test-jdk17:
    name: "Test JDK17"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build
        run: make classes
      - name: Run
        run: make SKIP_AGENT_TESTS=1 all
