name: "test"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  test-jdk7:
    name: "Test JDK7"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
      - name: Build
        run: make classes
      - name: Run
        run: make all

  test-jdk8:
    name: "Test JDK8"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: make classes
      - name: Run
        run: make all

  test-jdk11:
    name: "Test JDK11"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: make classes
      - name: Run
        run: make all
